apiVersion: v1
kind: Pod
metadata:
  name: pyspark-job
  labels:
    app: pyspark
spec:
  containers:
  - name: pyspark-container
    image: your-spark-image:latest
    command: ["/bin/bash", "-c", "/opt/spark/bin/spark-submit --master k8s://<KUBERNETES_MASTER> \
      --deploy-mode cluster \
      --name pyspark-job \
      --conf spark.executor.instances=2 \
      --conf spark.kubernetes.container.image=your-spark-image:latest \
      --conf spark.kubernetes.namespace=default \
      --conf spark.kubernetes.driver.pod.name=pyspark-job-driver \
      --conf spark.jars=/image/templocation/custom_jar/custom.jar \
      local:///image/templocation/app/main.py"]
    ports:
      - containerPort: 4040  # Exposing Spark UI port
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"
  restartPolicy: Never
